### ISSUE TITLE
Bringing up Moonstone instead of the tetra toolbooster - 1.20.1

### ISSUE THREAD

**Issue by ghost** [Syrikal/Tetra-Toolbooster#1]
Hello, I'll add some screenshots below to visualize the issue.

In my 1.20.1 modpack featuring every tetra mod available, I try to use the toolbooster in the hammer socket and it's currently trying to apply itself as a moonstone, thus not providing the boost as promised.

Screenshots below

![2024-10-31_18 36 00](https://github.com/user-attachments/assets/bbf32478-7fc8-4abe-8725-12e6a0ff8c5d)
![2024-10-31_18 38 00](https://github.com/user-attachments/assets/02a1dd6c-5ea0-40ed-b8fa-eb1a7372384a)

**Comment by ghost** [comment]
Ok turns out uninstalling and reinstalling just simply fixes it.

**Comment by ghost** [comment]
Thank you for the helpful mod, love it to and thorugh!

**Comment by hypnotica0** [comment]
hello, i'm having the same issue but can't seem to fix it, what exactly did you do?
